USE db_autogenerated;

SELECT * FROM mytable;

SELECT postalZip AS 'Codigo Postal', region AS 'Region', country AS 'Pais' from mytable;

SELECT * FROM mytable WHERE phone LIKE '(811)%';

SELECT * FROM mytable WHERE country IN ('Italy','Spain');

SELECT COUNT(*) FROM mytable;

SELECT id FROM mytable WHERE country IN ('Germany','Turkey');

SELECT region, country, postalZip FROM mytable WHERE id IN (SELECT id FROM mytable WHERE country IN ('Germany','Turkey'));

SELECT MIN(id), MAX(id) FROM mytable;

SELECT country, COUNT(*) AS Total FROM mytable GROUP BY country;

SELECT * FROM mytable ORDER BY postalZip LIMIT 10;

DELETE FROM mytable WHERE country LIKE 'Singapore';

